version: '3.8'

services:
  php:
    image: php:8.2-fpm
    container_name: symfony_php
    build: ./docker/php
    volumes:
      - ./app:/var/www/symfony/app
    environment:
      XDEBUG_CONFIG: "remote_host=10.10.13.1, remote_enable=1"
      PHP_IDE_CONFIG: "serverName=litvinov.local"
    extra_hosts:
      - "172.17.0.1:host-gateway"
    expose:
      - 9003
      - 9000
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/symfony/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - internal

  db:
    image: mysql:latest
    container_name: symfony-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_pass
#    volumes:
#      - db_data:/var/lib/mysql
    networks:
      - internal
    ports:
      - "3306:3306"
networks:
  internal:
    name: litvinov
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.10.13.0/24
          gateway: 10.10.13.1